name: PHPUnit (php-actions)
description: Run your PHPUnit tests in your Github Actions.

inputs:
  version:
    description: What version of PHPUnit to use
    default: latest
    required: false

  php_version:
    description: What version of PHP to use
    default: latest
    required: false

  php_extensions:
    description: Space separated list of extensions to configure with the PHP build
    required: false

  vendored_phpunit_path:
    description: Path to a vendored phpunit binary
    required: false

  configuration:
    description: Configuration file location
    required: false

  log_junit:
    description: JUnit output file location
    required: false

  log_teamcity:
    description: JUnit output file location
    required: false

  testdox_html:
    description: JUnit output file location
    required: false

  testdox_text:
    description: JUnit output file location
    required: false

  testdox_xml:
    description: JUnit output file location
    required: false

  memory_limit:
    description: Memory limit
    required: false

  bootstrap:
    description: Path to bootstrap file
    required: false

  filter:
    description: Filter which tests to run
    required: false

  testsuite:
    description: Specify a testsuite to run
    required: false

  group:
    description: Only runs tests from the specified group(s)
    required: false

  exclude_group:
    description: Exclude tests from the specified group(s)
    required: false

  test_suffix:
    description: Only search for test in files with specified suffix(es)
    required: false
    default: Test.php,.phpt

  whitelist:
    description: Path to directory to whitelist for code coverage analysis
    required: false

  args:
    description: Extra arguments to pass to the phpunit binary
    required: false

runs:
  using: "composite"
  steps:
    - env:
        ACTION_TOKEN: ${{ github.token }}
        ACTION_VERSION: ${{ inputs.version }}
        ACTION_PHP_VERSION: ${{ inputs.php_version }}
        ACTION_PHP_EXTENSIONS: ${{ inputs.php_extensions }}
        ACTION_PHPUNIT_PATH: ${{ inputs.vendored_phpunit_path }}
        ACTION_CONFIGURATION: ${{ inputs.configuration }}
        ACTION_LOG_JUNIT: ${{ inputs.log_junit }}
        ACTION_TESTDOX_HTML: ${{ inputs.testdox_html }}
        ACTION_TESTDOX_TEXT: ${{ inputs.testdox_text }}
        ACTION_TESTDOX_XML: ${{ inputs.testdox_xml }}
        ACTION_BOOTSTRAP: ${{ inputs.bootstrap }}
        ACTION_FILTER: ${{ inputs.filter }}
        ACTION_TESTSUITE: ${{ inputs.testsuite }}
        ACTION_GROUP: ${{ inputs.group }}
        ACTION_EXCLUDE_GROUP: ${{ inputs.exclude_group }}
        ACTION_TEST_SUFFIX: ${{ inputs.test_suffix }}
        ACTION_WHITELIST: ${{ inputs.whitelist }}
        ACTION_MEMORY_LIMIT: ${{ inputs.memory_limit }}
        ACTION_ARGS: ${{ inputs.args }}
      id: phpunit_run
      run: bash <(curl -s https://raw.githubusercontent.com/php-actions/php-build/330b13bbb1eadd05bbb627477c1549cd7e62e406/php-build.bash) phpunit \
        && ${{ github.action_path }}/phpunit-action.bash || { echo "::group::Debug output" ; cat ${{ github.workspace }}/output.log ; echo "::endgroup::" ; exit 1; }
      shell: bash

branding:
  icon: 'check-square'
  color: 'purple'
