#!/bin/bash
set -e

if [ "$1" = "latest" ]
then
	version=9
else
	version=$1
fi

phpunit_bin="/usr/local/bin/phpunit-$version"

if test -f $phpunit_bin
then
	rm -f /usr/local/bin/phpunit
	ln -s "$phpunit_bin" "/usr/local/bin/phpunit"
	echo "Successfully linked $phpunit_bin"
else
	echo "Error linking $phpunit_bin: version doesn't exit"
	exit 1
fi